import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Taskss",
  description: "Generated by create next app",
};

export default function TasksPage() {
  return (
    <main>
      <div>Tasks</div>
    </main>
  );
}
